name: "Conventional Commits Check"
description: "Ensures that all commit messages in a Pull Request are following the conventional-commits standard."
branding:
  icon: "check-square"
runs:
  using: node12
  main: dist/main/index.js
inputs:
  github-token: 
    required: true
    description: Github token
  valid-commit-types: 
    required: false
    description: List of valid commit types
